output_directory: ../results
model_name: VAESDR
model_params:
  hidden_size: 32
  emb_size: 16
  clf_hidden_1: 0
  clf_hidden_2: 0
  dropout: 0.1
optim_params:
  lr: 0.001
  l2_reg: 0.001
hyperparameters:
  rc_x_loss: 0.00001
  rc_z_loss: 0.00001
  kl_loss: 0.0001
  discriminator_loss: 0
  second_pass_loss: 0
dataset_path: ../dataset/ABIDE/meta.csv
dataset_name: ABIDE
seeds:
  - 0
  - 1
  - 2
  - 3
  - 4
  - 5
  - 6
  - 7
  - 8
  - 9
num_fold: 5
ssl: true
harmonize: false
labeled_sites: NYU
device: 3
verbose: true
max_epoch: 10
patience: 1000
save_model: true