seed:
  min: 0
  max: 10
fold:
  min: 0
  max: 5
model:
  -
    model_name: ASDSAENet
    model_params:
      ae_param:
        emb_size: 4975
      fcnn_param:
        input_size: 4975
        hidden_1: 2487
        hidden_2: 500
    hyperparameters:
      ae_param:
        beta: 2
        p: 0.05
    optim_params:
      ae_param:
        lr: 0.0001
        l2_reg: 0.0001
      fcnn_param:
        lr: 0.0001
        l2_reg: 0.0001
  -
    model_name: ASDSAENet1
    model_params:
      ae_param:
        emb_size: 4975
        mask_ratio: 0.5
      fcnn_param:
        input_size: 4975
        hidden_1: 2487
        hidden_2: 500
    hyperparameters:
      ae_param:
        beta: 2
        p: 0.05
    optim_params:
      ae_param:
        lr: 0.0001
        l2_reg: 0.0001
      fcnn_param:
        lr: 0.0001
        l2_reg: 0.0001
data:
  -
    dataset: ABIDE
    labeled_sites:
      - 
        - NYU
        - CALTECH
        - LEUVEN_1
        - LEUVEN_2
        - MAX_MUN
        - OHSU
        - OLIN
        - PITT
        - STANFORD
        - TRINITY
        - UCLA_1
        - UCLA_2
        - UM_1
        - UM_2
        - USM
        - YALE
      - NYU
      - CALTECH
      - LEUVEN_1
      - LEUVEN_2
      - MAX_MUN
      - OHSU
      - OLIN
      - PITT
      - STANFORD
      - TRINITY
      - UCLA_1
      - UCLA_2
      - UM_1
      - UM_2
      - USM
      - YALE
  -
    dataset: ADHD
    labeled_sites:
      -
        - NYU
        - PKU
        - NI
        - OHSU
      - NYU
      - PKU
      - NI
      - OHSU
experiment_settings:
  -
    ssl: false
    harmonize: false
    validation: false
process:
  device: 1
  verbose: false
