seed:
  min: 0
  max: 1 # max not included
fold:
  min: 0
  max: 5 # max not included
model:
  -
    model_name: VAECH-II
    model_params:
      hidden_size: 300
      emb_size: 150
      clf_hidden_1: 50
      clf_hidden_2: 30
      dropout: 0.5
    hyperparameters:
      rc_loss: 0.00001
      kl_loss: 0.001
      ch_loss: 10
    optim_params:
      lr:
        ch: 0.005
        vae_ffn: 0.0001
      l2_reg:
        ch: 0.0
        vae_ffn: 0.001
  -
    model_name: VAECH-I
    model_params:
      hidden_size: 300
      emb_size: 150
      clf_hidden_1: 50
      clf_hidden_2: 30
      dropout: 0.5
    hyperparameters:
      rc_loss: 0.00001
      kl_loss: 0.001
      ch_loss: 1
    optim_params:
      lr: 0.0001
      l2_reg: 0.001
  -
    model_name: VAECH
    model_params:
      hidden_size: 300
      emb_size: 150
      clf_hidden_1: 50
      clf_hidden_2: 30
      dropout: 0.5
    hyperparameters:
      rc_loss: 0.00001
      kl_loss: 0.001
      ch_loss: 1
    optim_params:
      lr: 0.0001
      l2_reg: 0.001
data:
  -
    dataset: ABIDE
    labeled_sites:
      - NYU
  -
    dataset: ADHD
    labeled_sites:
      - NYU
experiment_settings:
  # -
  #   ssl: false
  #   harmonize: false
  #   validation: false
  -
    ssl: true
    harmonize: false
    validation: false
  # -
  #   ssl: true
  #   harmonize: true
  #   validation: false
process:
  device: 2
  verbose: false
  save_model_condition: # OR
    -
      # AND
      dataset: ABIDE
      labeled_sites: NYU
    -
      dataset: ADHD
      labeled_sites: NYU
    -
      dataset: ADHD
      labeled_sites: PKU
