-
  model_name: VAE-FFN
  model_params:
    hidden_size: 300
    emb_size: 150
    clf_hidden_1: 50
    clf_hidden_2: 30
    dropout: 0.5
  optim_params:
    lr: 0.0001
    l2_reg: 0.001
  hyperparameters:
    rc_loss: 0.00001
    kl_loss: 0.001
  dataset: ABIDE
  ssl: true
  harmonize: true
  validation: false
  labeled_sites: NYU
  device: 2
  verbose: true
  save_model: true
