seed:
  min: 0
  max: 10
fold:
  min: 0
  max: 5
model:
  -
    model_name: VAE-FFN
    model_params:
      hidden_size: 300
      emb_size: 150
      clf_hidden_1: 50
      clf_hidden_2: 30
      dropout: 0.5
    hyperparameters:
      rc_loss: 0.00001
      kl_loss: 0.001
    optim_params:
      lr: 0.0001
      l2_reg: 0.001
data:
  -
    output_directory: ../.archive/ABIDE_WHOLE
    dataset: ABIDE
    labeled_sites:
      - 
        - NYU
        - CALTECH
        - LEUVEN_1
        - LEUVEN_2
        - MAX_MUN
        - OHSU
        - OLIN
        - PITT
        - STANFORD
        - TRINITY
        - UCLA_1
        - UCLA_2
        - UM_1
        - UM_2
        - USM
        - YALE
  -
    output_directory: ../.archive/ADHD_WHOLE
    dataset: ADHD
    labeled_sites:
      -
        - NYU
        - PKU
        - NI
        - OHSU
experiment_settings:
  -
    ssl: false
    harmonize: false
    validation: false
  -
    ssl: false
    harmonize: true
    validation: false
process:
  device: 2
  verbose: false
