seed:
  min: 0
  max: 10
fold:
  min: 0
  max: 5
model:
  -
    model_name: VAECH-II
    model_params:
      hidden_size: 32
      emb_size: 16
      clf_hidden_1: 0
      clf_hidden_2: 0
      dropout: 0.2
    hyperparameters:
      rc_loss: 0.0001
      kl_loss: 0.001
      ch_loss: 0.001
      alpha_loss: true
    optim_params:
      lr: 0.001
      l2_reg: 0.001
data:
  -
    output_directory: ../.archive/ABIDE_WHOLE
    dataset: ABIDE
    labeled_sites:
      - 
        - NYU
        - CALTECH
        - LEUVEN_1
        - LEUVEN_2
        - MAX_MUN
        - OHSU
        - OLIN
        - PITT
        - STANFORD
        - TRINITY
        - UCLA_1
        - UCLA_2
        - UM_1
        - UM_2
        - USM
        - YALE
  -
    output_directory: ../.archive/ADHD_WHOLE
    dataset: ADHD
    labeled_sites:
      -
        - NYU
        - PKU
        - NI
        - OHSU
experiment_settings:
  -
    ssl: false
    harmonize: false
    validation: false
process:
  device: 2
  verbose: false
  max_epoch: 1000
  patience: 1000
  save_model_condition:
    -
      dataset: ABIDE
    -
      dataset: ADHD
