seed:
  min: 0
  max: 10
fold:
  min: 0
  max: 5
model:
  -
    model_name: GCN-FCNN
    model_params:
      emb1: 94
      emb2: 0
      tau: 0.25
      num_nodes: 264
      clf_hidden_size:
        - 128
        - 264
    optim_params:
      gcn:
        lr: 0.0001
        l2_reg: 0.0001
      fcnn:
        lr: 0.0001
        l2_reg: 0.0001
data:
  -
    output_directory: ../.archive/ABIDE_INDIVIDUAL
    dataset: ABIDE
    labeled_sites:
      - NYU
      - CALTECH
      - LEUVEN_1
      - LEUVEN_2
      - MAX_MUN
      - OHSU
      - OLIN
      - PITT
      - STANFORD
      - TRINITY
      - UCLA_1
      - UCLA_2
      - UM_1
      - UM_2
      - USM
      - YALE
  -
    output_directory: ../.archive/ADHD_INDIVIDUAL
    dataset: ADHD
    labeled_sites:
      - NYU
      - PKU
      - NI
      - OHSU
experiment_settings:
  -
    ssl: false
    harmonize: false
    validation: false
process:
  device: 2
  verbose: false
  max_epoch: 400
  dataloader_num_process: 10
  save_model_condition:
    -
      dataset: ABIDE
      labeled_sites: NYU
    -
      dataset: ADHD
      labeled_sites: NYU
    -
      dataset: ADHD
      labeled_sites: PKU
